// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.9
// source: standard/v1/standard.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Agent_AlgoCallback_FullMethodName          = "/standard.v1.Agent/AlgoCallback"
	Agent_ReplaceAlgorithmModel_FullMethodName = "/standard.v1.Agent/ReplaceAlgorithmModel"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	// 算法回调，用于上传算法输出结果
	AlgoCallback(ctx context.Context, in *AlgoOutput, opts ...grpc.CallOption) (*AlgoOutputResponse, error)
	// agent_config，替换algorithm.model
	ReplaceAlgorithmModel(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*ReplaceResponse, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) AlgoCallback(ctx context.Context, in *AlgoOutput, opts ...grpc.CallOption) (*AlgoOutputResponse, error) {
	out := new(AlgoOutputResponse)
	err := c.cc.Invoke(ctx, Agent_AlgoCallback_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ReplaceAlgorithmModel(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*ReplaceResponse, error) {
	out := new(ReplaceResponse)
	err := c.cc.Invoke(ctx, Agent_ReplaceAlgorithmModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility
type AgentServer interface {
	// 算法回调，用于上传算法输出结果
	AlgoCallback(context.Context, *AlgoOutput) (*AlgoOutputResponse, error)
	// agent_config，替换algorithm.model
	ReplaceAlgorithmModel(context.Context, *ReplaceRequest) (*ReplaceResponse, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (UnimplementedAgentServer) AlgoCallback(context.Context, *AlgoOutput) (*AlgoOutputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlgoCallback not implemented")
}
func (UnimplementedAgentServer) ReplaceAlgorithmModel(context.Context, *ReplaceRequest) (*ReplaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceAlgorithmModel not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_AlgoCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlgoOutput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AlgoCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_AlgoCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AlgoCallback(ctx, req.(*AlgoOutput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ReplaceAlgorithmModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ReplaceAlgorithmModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ReplaceAlgorithmModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ReplaceAlgorithmModel(ctx, req.(*ReplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "standard.v1.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AlgoCallback",
			Handler:    _Agent_AlgoCallback_Handler,
		},
		{
			MethodName: "ReplaceAlgorithmModel",
			Handler:    _Agent_ReplaceAlgorithmModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "standard/v1/standard.proto",
}
