// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.9
// source: warning/v1/warning.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SacService_SendMsg_FullMethodName = "/warning.v1.SacService/SendMsg"
)

// SacServiceClient is the client API for SacService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SacServiceClient interface {
	SendMsg(ctx context.Context, in *Frame, opts ...grpc.CallOption) (*Response, error)
}

type sacServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSacServiceClient(cc grpc.ClientConnInterface) SacServiceClient {
	return &sacServiceClient{cc}
}

func (c *sacServiceClient) SendMsg(ctx context.Context, in *Frame, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, SacService_SendMsg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SacServiceServer is the server API for SacService service.
// All implementations must embed UnimplementedSacServiceServer
// for forward compatibility
type SacServiceServer interface {
	SendMsg(context.Context, *Frame) (*Response, error)
	mustEmbedUnimplementedSacServiceServer()
}

// UnimplementedSacServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSacServiceServer struct {
}

func (UnimplementedSacServiceServer) SendMsg(context.Context, *Frame) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}
func (UnimplementedSacServiceServer) mustEmbedUnimplementedSacServiceServer() {}

// UnsafeSacServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SacServiceServer will
// result in compilation errors.
type UnsafeSacServiceServer interface {
	mustEmbedUnimplementedSacServiceServer()
}

func RegisterSacServiceServer(s grpc.ServiceRegistrar, srv SacServiceServer) {
	s.RegisterService(&SacService_ServiceDesc, srv)
}

func _SacService_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Frame)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SacServiceServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SacService_SendMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SacServiceServer).SendMsg(ctx, req.(*Frame))
	}
	return interceptor(ctx, in, info, handler)
}

// SacService_ServiceDesc is the grpc.ServiceDesc for SacService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SacService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warning.v1.SacService",
	HandlerType: (*SacServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMsg",
			Handler:    _SacService_SendMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "warning/v1/warning.proto",
}
